<Project>

  <PropertyGroup Condition="'$(_WWUI_PlatformPropsLoaded)' == ''">
    <_WWUI_PlatformPropsLoaded>true</_WWUI_PlatformPropsLoaded>

    <WWUIPlatform Condition="'$(WWUIPlatform)' == '' And $([MSBuild]::IsOSPlatform('Windows'))">Windows</WWUIPlatform>
    <WWUIPlatform Condition="'$(WWUIPlatform)' == '' And $([MSBuild]::IsOSPlatform('Linux'))">Linux</WWUIPlatform>
    <WWUIPlatform Condition="'$(WWUIPlatform)' == '' And $([MSBuild]::IsOSPlatform('OSX'))">MacOS</WWUIPlatform>
    <WWUIPlatform Condition="'$(WWUIPlatform)' == ''">Windows</WWUIPlatform>

    <TargetFramework Condition="'$(WWUIPlatform)' == 'Windows'">net10.0</TargetFramework>
    <TargetFramework Condition="'$(WWUIPlatform)' == 'MacOS'">net10.0-macos</TargetFramework>
    <TargetFramework Condition="'$(WWUIPlatform)' == 'Linux'">net10.0</TargetFramework>

    <DefineConstants Condition="'$(WWUIPlatform)' == 'Windows'">$(DefineConstants);WINDOWS</DefineConstants>
    <DefineConstants Condition="'$(WWUIPlatform)' == 'Linux'">$(DefineConstants);LINUX</DefineConstants>
    <DefineConstants Condition="'$(WWUIPlatform)' == 'MacOS'">$(DefineConstants);MACOS</DefineConstants>
  </PropertyGroup>

</Project>
