// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 TodoListModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel, ModelCommandHost } from 'webwindowui-bridge';
import descriptorJson from '../bridge/todo_list_model.json';
import { TodoItemModel } from './TodoItemModel';

export class TodoListModel extends ModelCommandHost {
  /** typed-repeated 序数键契约：属性名 → { proto 字段号: 元素属性名 }（与 .NET
      ConvertToModelValue/ConvertFromModelValue 的 ordinalFields int 键对称）。构建期
     烘焙、桥直接读取，不做运行时 constructor.name 反射（class 名会被压缩器改名）。
     声明与访问均用字符串字面量键：minifier 不改写字面量。 */
  static ['__repeatedFields'] = {
    items: { 1: 'title', 2: 'done', 3: 'priority', 4: 'createdAt' },
  }

  /** items：任务列表：前端强类型 TodoItemModel[]，勾选/增删即整列表回写。 */
  items: TodoItemModel[] = []

  /** newTitle：新增输入框（前端 v-model 双向回写）。 */
  newTitle: string = ''

  /** status：保存状态提示（如「已保存 12:03:45（5 项）」）。 */
  status: string = ''

  /** AddTitle：新增任务：前端 model.addTitle(标题) → 命令 → 加入列表 + 持久化 + 整列自动推送。 */
  addTitle(arg: string): void { this._commandChannel?.('AddTitle', arg) }
  /** Toggle：切换完成状态：前端 model.toggle(全列表下标) → 命令 → 改 Done + 持久化。 */
  toggle(arg: number): void { this._commandChannel?.('Toggle', arg) }
  /** Remove：删除任务：前端 model.remove(全列表下标) → 命令 → 移除 + 持久化。 */
  remove(arg: number): void { this._commandChannel?.('Remove', arg) }
  /** ClearCompleted：清除已完成：前端 model.clearCompleted() → 命令 → 批量移除 + 持久化。 */
  clearCompleted(): void { this._commandChannel?.('ClearCompleted') }
}

/** 绑定 TodoListModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindTodoListModel(): TodoListModel {
  return bindModel(new TodoListModel(), descriptorJson);
}
