// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 TodoItemModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/todo_item_model.json';
export class TodoItemModel {
  /** title：任务标题。 */
  title: string = ''

  /** done：是否完成。 */
  done: boolean = false

  /** priority：优先级 1-3（1 高）。 */
  priority: number = 0

  /** createdAt：创建时间（格式化字符串，与 .NET 时间戳对应）。 */
  createdAt: string = ''

}

/** 绑定 TodoItemModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindTodoItemModel(): TodoItemModel {
  return bindModel(new TodoItemModel(), descriptorJson);
}
