// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NotesModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel, ModelCommandHost } from 'webwindowui-bridge';
import descriptorJson from '../bridge/notes_model.json';
import { NoteModel } from './NoteModel';

export class NotesModel extends ModelCommandHost {
  /** notes：get-only ObservableCollection（免 [ObservableProperty]），原地增删自动推送整列表。 */
  notes: NoteModel[] = []

  /** input：与各窗口输入框双向绑定；发送后由命令清空并推回。 */
  input: string = ''

  /** status */
  status: string = ''

  /** total */
  total: number = 0

  /** Send：发送便签：把 Input 追加进 Notes（同模型多窗口即时广播），随后清空输入。 */
  send(): void { this._commandChannel?.('Send') }
  /** Remove：按序数键删除指定位置的便签（typed repeated 双向：前端传 index）。 */
  remove(arg: number): void { this._commandChannel?.('Remove', arg) }
}

/** 绑定 NotesModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNotesModel(): NotesModel {
  return bindModel(new NotesModel(), descriptorJson);
}
