<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="cef.runtime.linux-arm64" Version="150.0.11" />
    <PackageVersion Include="cef.runtime.linux-x64" Version="150.0.11" />
    <PackageVersion Include="cef.runtime.osx-arm64" Version="150.0.11" />
    <PackageVersion Include="cef.runtime.osx-x64" Version="150.0.11" />
    <PackageVersion Include="CefGlue.Next.BrowserProcess.Core" Version="150.7871.115" />
    <PackageVersion Include="CefGlue.Next.Common" Version="150.7871.115" />
    <PackageVersion Include="CefGlue.Next.Common.Shared" Version="150.7871.115" />
    <PackageVersion Include="chromiumembeddedframework.runtime.win-arm64" Version="150.0.11" />
    <PackageVersion Include="chromiumembeddedframework.runtime.win-x64" Version="150.0.11" />
    <PackageVersion Include="WebWindowUI" Version="$(Version)" />
    <PackageVersion Include="WebWindowUI.Backend" Version="$(Version)" />
    <PackageVersion Include="WebWindowUI.Frontend" Version="$(Version)" />
    <PackageVersion Include="WebWindowUI.Platforms.Windows" Version="$(Version)" />
    <PackageVersion Include="WebWindowUI.Platforms.Cef" Version="$(Version)" />
    <PackageVersion Include="WebWindowUI.Platforms.Linux" Version="$(Version)" />
    <PackageVersion Include="WebWindowUI.Platforms.MacOS" Version="$(Version)" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="GirCore.GLib-2.0" Version="0.8.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageVersion Include="protobuf-net" Version="3.2.56" />
    <PackageVersion Include="SharpCompress" Version="0.50.4" />
    <PackageVersion Include="CefGlue.Next.Core" Version="150.7871.115" />
    <PackageVersion Include="System.Text.Json" Version="8.0.6" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>