<Project>

  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>Color_yr</Authors>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)WebWindowUI\WebWindowUI.Platform.props" />

  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

</Project>
