<Project>
  <Import Project="$(MSBuildThisFileDirectory)WebWindowUI.targets"
          Condition="'$(_WebWindowUITargetsLoaded)' == ''" />
  <ItemGroup>
    <_WWUI_RepoBackendRef Include="@(ProjectReference->WithMetadataValue('Filename', 'WebWindowUI.Backend'))" />
  </ItemGroup>
  <ItemGroup Condition="'@(_WWUI_RepoBackendRef)' != ''">
    <Analyzer Include="$(MSBuildThisFileDirectory)WebWindowUI.Generator.SourceGen\bin\$(Configuration)\netstandard2.0\WebWindowUI.Generator.SourceGen.dll" />
  </ItemGroup>

</Project>
