// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 MonitorModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/monitor_model.json';
import { ProcessModel } from './ProcessModel';

export class MonitorModel {
  /** cpuUsage：CPU 使用率（%）。 */
  cpuUsage: number = 0

  /** memoryUsage：内存占用（%）。 */
  memoryUsage: number = 0

  /** uptime：已运行时长（人类可读）。 */
  uptime: string = ''

  /** processes：get-only ObservableCollection（免 [ObservableProperty]），原地清空重建自动推送整列表。 */
  processes: ProcessModel[] = []

  /** settings：嵌套设置子模型（ModelValue 下发；设置窗口绑定同一实例强类型编辑）。 */
  settings: Record<string, unknown> = {}

}

/** 绑定 MonitorModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindMonitorModel(): MonitorModel {
  return bindModel(new MonitorModel(), descriptorJson);
}
