<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<UseCEF>false</UseCEF>
    <ApplicationManifest Condition="'$(WWUIPlatform)' == 'Windows' And '$(UseCEF)' == 'true'">app.manifest</ApplicationManifest>
    <ApplicationId Condition="'$(WWUIPlatform)' == 'MacOS'">com.webwindowui.demo.todo</ApplicationId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Properties\PublishProfiles\FolderProfile.pubxml.user" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="WebWindowUI" />
    <ProjectReference Include="..\WebWindowUI.Demo.Todo.Backend\WebWindowUI.Demo.Todo.Backend.csproj" />
    <ProjectReference Include="..\WebWindowUI.Demo.Todo.Frontend\WebWindowUI.Demo.Todo.Frontend.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
