<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultItems>false</EnableDefaultItems>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WebWindowUI.Frontend" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="src\**\*" />
    <None Include="public\**\*" />
    <None Include="package.json" />
    <None Include="package-lock.json" />
    <None Include="tsconfig.json" />
    <None Include="vite.config.ts" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
