<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <ApplicationManifest>app.manifest</ApplicationManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\temp_code\CefGlue\CefGlue\CefGlue.csproj" />
    <ProjectReference Include="..\..\..\temp_code\CefGlue\CefGlue.BrowserProcess.Core\CefGlue.BrowserProcess.Core.csproj" />
  </ItemGroup>

</Project>
