<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<UseCEF>true</UseCEF>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
    <ApplicationId Condition="'$(WWUIPlatform)' == 'MacOS'">com.webwindowui.sample</ApplicationId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebWindowUI.Sample.Backend\WebWindowUI.Sample.Backend.csproj" />
    <ProjectReference Include="..\WebWindowUI.Sample.Frontend\WebWindowUI.Sample.Frontend.csproj" />
    <ProjectReference Include="..\..\Core\WebWindowUI\WebWindowUI.csproj" />
  </ItemGroup>

</Project>
