<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject Condition="'$(WWUIPlatform)' == 'Linux'">true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\WebWindowUI.Core\WebWindowUI.Core.csproj" />
    <ProjectReference Include="..\..\Sample\WebWindowUI.Sample.Backend\WebWindowUI.Sample.Backend.csproj" />
    <ProjectReference Include="..\..\Sample\WebWindowUI.Sample\WebWindowUI.Sample.csproj" Condition="'$(WWUIPlatform)' != 'MacOS'" />
    <ProjectReference Include="..\..\Platforms\WebWindowUI.Platforms.Linux\WebWindowUI.Platforms.Linux.csproj" />
  </ItemGroup>

</Project>
