// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NestedItemTagModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../../bridge/nested_item_tag_model.json';
export class NestedItemTagModel {
  /** name：标签名（proto 字段号 1）。 */
  name: string = ''

}

/** 绑定 NestedItemTagModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNestedItemTagModel(): NestedItemTagModel {
  return bindModel(new NestedItemTagModel(), descriptorJson);
}
