// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NestedItemTagModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../../bridge/nested_item_tag_model.json';
export class NestedItemTagModel {
  /** 线缆协议契约（构建期定死、桥直接读取）：modelId = 模型序号（线缆上代替消息名），
      full/update = descriptor 消息类型名（解码用）。字符串字面量键：压缩器不改写。 */
  static ['__protocol'] = { modelId: 1439038918, full: 'webwindowui.model.generated.NestedItemTagModel', update: 'webwindowui.model.generated.NestedItemTagModelUpdate' }
  /** name：标签名（proto 字段号 1）。 */
  name: string = ''

}

/** 绑定 NestedItemTagModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNestedItemTagModel(): NestedItemTagModel {
  return bindModel(new NestedItemTagModel(), descriptorJson);
}
