// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NestedListItemModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../../bridge/nested_list_item_model.json';
import { NestedItemTagModel } from './NestedItemTagModel';

export class NestedListItemModel {
  /** title：标题（proto 字段号 1）。 */
  title: string = ''

  /** done：是否完成（proto 字段号 2）。 */
  done: boolean = false

  /** priority：优先级（proto 字段号 3）。 */
  priority: number = 0

  /** tags：内层标签列表：typed repeated（嵌套 List&lt;Model&gt;，proto 字段号 4）。 */
  tags: NestedItemTagModel[] = []

  /** meta：内层单模型（ModelValue 兜底 / 序数键，proto 字段号 5，只读展示）。 */
  meta: Record<string, unknown> = {}

}

/** 绑定 NestedListItemModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNestedListItemModel(): NestedListItemModel {
  return bindModel(new NestedListItemModel(), descriptorJson);
}
