// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 ImageGalleryModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel, ModelCommandHost } from 'webwindowui-bridge';
import descriptorJson from '../bridge/image_gallery_model.json';
import { ImageItemModel } from './ImageItemModel';

export class ImageGalleryModel extends ModelCommandHost {
  /** items：图片列表：get-only ObservableCollection（免 [ObservableProperty]），原地增删自动推前端。 */
  items: ImageItemModel[] = []

  /** status：状态提示（如「已保存 xxx.png（12 KB）」）。 */
  status: string = ''

  /** storeDir：存储目录（%LocalAppData%\WebWindowUI.Demo.ImageGallery\images）。 */
  storeDir: string = ''

  /** UploadBytes：模式一 · 字节上传：前端把文件读成 byte[] 经命令参数回传（{ Name, Data } 对象 → 反射重建 UploadFile）， .NET 把字节写盘（同名自动加序号）后插到列表头部，补丁差量推送前端。 */
  uploadBytes(arg: unknown): void { this._commandChannel?.('UploadBytes', arg) }
  /** PickFile：模式二 · 路径上传（系统原生文件选择器）：前端点「路径上传」→ 本命令在 .NET 侧弹系统原生 OpenFileDialog（Windows）选文件 → 直接读源文件拷入存储目录（源文件不动）。非 Windows 平台 无原生对话框（状态提示）。 */
  pickFile(): void { this._commandChannel?.('PickFile') }
  /** Remove：删除图片：前端传列表下标 → 命令 → 删磁盘文件 + 移除条目（补丁差量推送）。 */
  remove(arg: number): void { this._commandChannel?.('Remove', arg) }
  /** Refresh：重新扫描存储目录（如外部放入图片后点刷新，后端重新发送图片）。 */
  refresh(): void { this._commandChannel?.('Refresh') }
}

/** 绑定 ImageGalleryModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindImageGalleryModel(): ImageGalleryModel {
  return bindModel(new ImageGalleryModel(), descriptorJson);
}
