// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 ImageItemModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/image_item_model.json';
export class ImageItemModel {
  /** name：磁盘文件名（含扩展名）。 */
  name: string = ''

  /** size：文件大小（字节）。 */
  size: number = 0

  /** modified：修改时间（格式化字符串，与 .NET 时间戳对应）。 */
  modified: string = ''

  /** path：文件地址（磁盘完整路径，如 C:\Users\…\images\sunset.png）。 */
  path: string = ''

  /** data：图片字节（png/jpg/gif/webp/…），前端按扩展名推断 MIME 后转 blob URL 渲染。 */
  data: Uint8Array = new Uint8Array()

}

/** 绑定 ImageItemModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindImageItemModel(): ImageItemModel {
  return bindModel(new ImageItemModel(), descriptorJson);
}
