// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 AboutModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/about_model.json';
export class AboutModel {
  /** appName：string：应用名。 */
  appName: string = ''

  /** version：string：版本号。 */
  version: string = ''

  /** buildDate：DateTime → string：构建日期。 */
  buildDate: string = ''

  /** repoUrl：string：仓库地址。 */
  repoUrl: string = ''

  /** contributors：List&lt;string&gt; → repeated string：贡献者。 */
  contributors: string[] = []

  /** features：string[] → repeated string：功能特性。 */
  features: string[] = []

  /** iconHash：byte[] → bytes：图标哈希。 */
  iconHash: Uint8Array = new Uint8Array()

  /** metadata：object（Dictionary）→ ModelValue：附加元数据。 */
  metadata: Record<string, unknown> = {}

}

/** 绑定 AboutModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindAboutModel(): AboutModel {
  return bindModel(new AboutModel(), descriptorJson);
}
