// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 LauncherModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel, ModelCommandHost } from 'webwindowui-bridge';
import descriptorJson from '../bridge/launcher_model.json';
export class LauncherModel extends ModelCommandHost {
  /** request：回写通道演示：值为要打开的窗口路径（"main"/"todos"/"multi"/…）；.NET 处理后清空。 与命令通道并存——前端 ModelSet 直接写属性（不经过命令），保留双向绑定回写的演示。 */
  request: string = ''

  /** buttonEnable：CanExecute 门控源：为 false 时 CommandWithArg 命令拒绝执行，前端按钮禁用。 */
  buttonEnable: boolean = false

  /** OpenWindow：无参命令：打开主窗口。 */
  openWindow(): void { this._commandChannel?.('OpenWindow') }
  /** CommandWithArg：带参命令：打开指定路径的窗口（CanExecute = ButtonEnable 门控）。 */
  commandWithArg(arg: string): void { this._commandChannel?.('CommandWithArg', arg) }
}

/** 绑定 LauncherModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindLauncherModel(): LauncherModel {
  return bindModel(new LauncherModel(), descriptorJson);
}
