// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 MainWindowModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/main_window_model.json';
export class MainWindowModel {
  /** 线缆协议契约（构建期定死、桥直接读取）：modelId = 模型序号（线缆上代替消息名），
      full/update = descriptor 消息类型名（解码用）。字符串字面量键：压缩器不改写。 */
  static ['__protocol'] = { modelId: 47062079, full: 'webwindowui.model.generated.MainWindowModel', update: 'webwindowui.model.generated.MainWindowModelUpdate' }
  /** name：与前端输入框双向绑定。 */
  name: string = ''

  /** count：由 .NET 定时器每秒更新，实时推送到前端。 */
  count: number = 0

  /** message：由 .NET 定时器定期改写，推送到前端。 */
  message: string = ''

  /** extra：object 属性示例：值必须是可 JSON 序列化/反序列化的（此处用字典）。 */
  extra: Record<string, unknown> = {}

}

/** 绑定 MainWindowModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindMainWindowModel(): MainWindowModel {
  return bindModel(new MainWindowModel(), descriptorJson);
}
