// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 MultiWindowModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/multi_window_model.json';
export class MultiWindowModel {
  /** name：可编辑字段：任一窗口回写后，共享实例的其余窗口经广播同步。 */
  name: string = ''

  /** count：由共享窗口 A（ownTimer）每秒递增，广播给所有绑定窗口。 */
  count: number = 0

  /** instanceId：只读标签属性：前端不能回写（无 setter），快照照常下发。 */
  instanceId: string = ''

}

/** 绑定 MultiWindowModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindMultiWindowModel(): MultiWindowModel {
  return bindModel(new MultiWindowModel(), descriptorJson);
}
