// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NestedParentModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel, ModelCommandHost } from 'webwindowui-bridge';
import descriptorJson from '../bridge/nested_parent_model.json';
export class NestedParentModel extends ModelCommandHost {
  /** 线缆协议契约（构建期定死、桥直接读取）：modelId = 模型序号（线缆上代替消息名），
      full/update = descriptor 消息类型名（解码用）。字符串字面量键：压缩器不改写。 */
  static ['__protocol'] = { modelId: 2133376449, full: 'webwindowui.model.generated.NestedParentModel', update: 'webwindowui.model.generated.NestedParentModelUpdate' }
  /** title：父窗口标题（普通字段，双向绑定）。 */
  title: string = ''

  /** detail：嵌套模型属性：单 POCO 属性，descriptor 里是 ModelValue 兜底（序数键，只读展示）。 */
  detail: Record<string, unknown> = {}

  /** OpenDetail */
  openDetail(): void { this._commandChannel?.(0) }
}

/** 绑定 NestedParentModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNestedParentModel(): NestedParentModel {
  return bindModel(new NestedParentModel(), descriptorJson);
}
