// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NestedListModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel, ModelCommandHost } from 'webwindowui-bridge';
import descriptorJson from '../bridge/nested_list_model.json';
import { NestedListItemModel } from './items/NestedListItemModel';

export class NestedListModel extends ModelCommandHost {
  /** typed-repeated 序数键契约：属性名 → { proto 字段号: 元素属性名 }（与 .NET
      ConvertToModelValue/ConvertFromModelValue 的 ordinalFields int 键对称）。构建期
     烘焙、桥直接读取，不做运行时 constructor.name 反射（class 名会被压缩器改名）。
     声明与访问均用字符串字面量键：minifier 不改写字面量。 */
  static ['__repeatedFields'] = {
    items: { 1: 'title', 2: 'done', 3: 'priority', 4: 'tags', 5: 'meta' },
  }

  /** title：窗口标题（普通字段，双向绑定）。 */
  title: string = ''

  /** items：元素列表：typed repeated（List&lt;NestedListItemModel&gt;），前端强类型数组。 显式 get-only 属性（不加 [ObservableProperty]）：前端整列回写经生成器原地清空重建。 */
  items: NestedListItemModel[] = []

  /** counts：ObservableDictionary（字典原地增删自动推送）：.NET 侧原地改自动推前端，前端原地改回写 .NET。 */
  counts: Record<string, unknown> = {}

  /** OpenItem */
  openItem(arg: number): void { this._commandChannel?.('OpenItem', arg) }
  /** Bump：把指定统计项 +1（演示 .NET 侧原地改字典自动推前端）。 */
  bump(arg: string): void { this._commandChannel?.('Bump', arg) }
}

/** 绑定 NestedListModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNestedListModel(): NestedListModel {
  return bindModel(new NestedListModel(), descriptorJson);
}
