// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 NestedDetailModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/nested_detail_model.json';
export class NestedDetailModel {
  /** name：名称（proto 字段号 1）。 */
  name: string = ''

  /** level：层级（proto 字段号 2）。 */
  level: number = 0

}

/** 绑定 NestedDetailModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindNestedDetailModel(): NestedDetailModel {
  return bindModel(new NestedDetailModel(), descriptorJson);
}
