// <auto-generated>
// 由 WebWindowUI.Generator 自动生成：.NET 模型 SettingsModel 的前端 TS 镜像。
// 类型映射：.NET string→string、int/long/double/float→number、bool→boolean、byte[]→Uint8Array、
// DateTime/Guid/TimeSpan→string、List<T>/T[]→T[]、List<模型>→模型[]、object/Dictionary/枚举→Record<string, unknown>|number。
// 修改模型类后重新构建即可更新，请勿手动编辑。
// </auto-generated>

import { bindModel } from 'webwindowui-bridge';
import descriptorJson from '../bridge/settings_model.json';
export class SettingsModel {
  /** 线缆协议契约（构建期定死、桥直接读取）：modelId = 模型序号（线缆上代替消息名），
      full/update = descriptor 消息类型名（解码用）。字符串字面量键：压缩器不改写。 */
  static ['__protocol'] = { modelId: 1849004351, full: 'webwindowui.model.generated.SettingsModel', update: 'webwindowui.model.generated.SettingsModelUpdate' }
  /** theme：string：主题（浅色/深色）。 */
  theme: string = ''

  /** autoSave：bool：自动保存。 */
  autoSave: boolean = false

  /** maxItems：int：每页最大条目数。 */
  maxItems: number = 0

  /** progress：double：同步进度。 */
  progress: number = 0

  /** totalBytes：long（int64）：已同步的字节数。 */
  totalBytes: number = 0

  /** instanceId：Guid → string：实例标识。 */
  instanceId: string = ''

  /** lastBackup：DateTime → string：上次备份时间（示例定时器每 3 秒推送一次）。 */
  lastBackup: string = ''

  /** keepHistory：TimeSpan → string：保留历史时长。 */
  keepHistory: string = ''

  /** syncMode：枚举 → ModelValue 兜底：同步模式。 */
  syncMode: number = 0

  /** tags：List&lt;string&gt; → repeated string：标签集合。 */
  tags: string[] = []

  /** config：object（Dictionary）→ ModelValue：扩展配置。 */
  config: Record<string, unknown> = {}

}

/** 绑定 SettingsModel：创建实例并经 webwindowui-bridge 连接 .NET 双向绑定（descriptor 已含基础信封）。 */
export function bindSettingsModel(): SettingsModel {
  return bindModel(new SettingsModel(), descriptorJson);
}
